version: '{build}'
skip_tags: true
image: Visual Studio 2019
configuration: Release
init:
- git config --global core.autocrlf false
install:
  - ps: mkdir -Force ".\build\" | Out-Null
build_script:
- ps: ./Build.ps1
test: off
artifacts:
- path: artifacts/Serilog.*.nupkg
only_commits:
  files:
    - serilog-sinks-loggly.sln
    - src/Serilog.Sinks.Loggly/
    - Build.ps1
    - assets/
    - test/Serilog.Sinks.Loggly.Tests/
    - appveyor.yml
deploy:
- provider: NuGet
  api_key:
    secure: N59tiJECUYpip6tEn0xvdmDAEiP9SIzyLEFLpwiigm/8WhJvBNs13QxzT1/3/JW/
  skip_symbols: true
  on:
    branch: /^(master|dev)$/
- provider: GitHub
  auth_token:
    secure: p4LpVhBKxGS5WqucHxFQ5c7C8cP74kbNB0Z8k9Oxx/PMaDQ1+ibmoexNqVU5ZlmX
  artifact: /Serilog.*\.nupkg/
  tag: v$(appveyor_build_version)
  on:
    branch: master
